CommunityPage/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.DependencyInjection;

namespace CommunityPage.Models
{
        public class ApplicationDbContext : DbContext
        {
            public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
                : base(options) { }

            public DbSet<ContactInfo> Contacts { get; set; }
        }
    
}

CommunityPage/Models/ContactInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace CommunityPage.Models
{
    public class ContactInfo 
    {
        [Key]
        public int ContactId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string UserMessage { get; set; } 

        internal void Sort(Func<object, object, int> p)
        {
            throw new NotImplementedException();
        }

        internal List<MessageBoards> ToList()
        {
            throw new NotImplementedException();
        }
    }
}

CommunityPage/Models/EFUserContact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommunityPage.Models
{
    public class EFUserContact : IUserRepository
    {
        private ApplicationDbContext context;

        public EFUserContact(ApplicationDbContext ctx)
        {
            context = ctx;
        }

        public IQueryable<ContactInfo> Contacts => context.Contacts;
    }
}

CommunityPage/Models/ErrorViewModel.cs
using System;

namespace CommunityPage.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CommunityPage/Models/IUserRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommunityPage.Models
{
    public interface IUserRepository
    {
        IQueryable<ContactInfo> Contacts { get; }
    }
}

CommunityPage/Models/MessageBoards.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace CommunityPage.Models
{
    public class MessageBoards
    {
            public int MessageId { get; set; }
            public List<ContactInfo> contactInfos = new List<ContactInfo>();
            public List<UserReply> reply = new List<UserReply>();

            public string UserName { get; set; }
            public string UserMessage { get; set; }

            public ICollection<UserReply> UserReply { get { return reply; } }

        internal void Sort(Func<object, object, int> p)
        {
            throw new NotImplementedException();
        }
    }

    }

CommunityPage/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace CommunityPage.Models
{
    public static class Repository
    {
        private static List<ContactInfo> responses = new List<ContactInfo>();
        

        public static IEnumerable<ContactInfo> Responses
        {
            get
            {
                return responses;
            }
        }
        public static void AddResponse(ContactInfo response)
        {
            responses.Add(response);
        }
        

    }
}

CommunityPage/Models/SeedData.cs
using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommunityPage.Models
{
    public class SeedData
    {
        public static void EnsurePopulated(IApplicationBuilder app)
        {
            ApplicationDbContext context = app.ApplicationServices
                .GetRequiredService<ApplicationDbContext>();
            context.Database.Migrate();
            if (!context.Contacts.Any())
            {
                context.Contacts.AddRange(
                    new ContactInfo
                    {
                        Name = "Bill",
                        Email = "numbone@gmail.com",
                        Phone = "555-555-5555",
                        UserMessage = "You're all going to lose."
                    }
                    
                );
                context.SaveChanges();
            }
        }
    }
}

CommunityPage/Models/UserReply.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommunityPage.Models
{
    public class UserReply
    {
            public int ReplyId { get; set; }
            public string CommentText { get; set; }
            public ContactInfo UserName { get; set; }
            public  ContactInfo UserMessage{ get; set; }

        internal List<UserReply> ToList()
        {
            throw new NotImplementedException();
        }
    }
    }

CommunityPage/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CommunityPage.Models;

namespace CommunityPage.Controllers
{
    public class HomeController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }

        public ViewResult History()
        {
            return View();
        }

        public ViewResult Info()
        {
            return View();
        }
        public ViewResult Important()
        {
            return View();
        }
        public ViewResult People()
        {
            ViewData["Founder"]= "Aaron McCarty";
            return View();
        }
        public ViewResult Thanks()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        [HttpGet]
        public ViewResult Contact()
        {
            return View();
        }
        [HttpPost]
        public ViewResult Contact(ContactInfo contactinfo)
        {
                Repository.AddResponse(contactinfo);
                return View("Thanks",contactinfo);
        }
        public ViewResult Messages()
        {
            return View(Repository.Responses);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CommunityPage/Controllers/Lab6Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;



namespace CommunityPage.Controllers
{
    public class Lab6Controller : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ContentResult TextTest()
        {
            return Content("This should Return this phrase as Content");
        }
        public RedirectResult RedirectTest()
        {
            return Redirect("https://www.google.com");
        }
        public EmptyResult EmptyData()
        {
            return new EmptyResult();
        }

        public IActionResult ClickBait()
        {
            return RedirectToPage("EmptyData");
        }
        
    }
}

CommunityPage/Controllers/UserReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CommunityPage.Models;
using Microsoft.AspNetCore.Mvc;

namespace CommunityPage.Controllers
{
    public class UserReplyController : Controller
    {
        [HttpGet]
        public ViewResult Replys()
        {
            ViewBag.Message = "All Replys are Reviewed";
            return View();
        }
        [HttpPost]
        public ViewResult Replys(ContactInfo reply)
        {
            List<MessageBoards> boards = reply.ToList();
            reply.Sort((c1, c2) => string.Compare(c1.ToString(), c2.ToString(), StringComparison.Ordinal));
            return View(boards);

        }
    }
}

CommunityPage/Views/Home/Contact.cshtml
@model CommunityPage.Models.ContactInfo 

@{
    Layout = "_DefaultLayout";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Contact</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="panel panel-success">
        <div class="panel-heading text-center"><h4>Want to join our league?</h4></div>
        <div class="panel-body">
            <form class="p-a-1" asp-action="Contact" method="post">
                <div class="form-group">
                    <label asp-for="Name"> Your Name please:</label>
                    <input class="form-control" asp-for="Name" />
                </div>
                <div class="form-group">
                    <label asp-for="Email"> Your Email please:</label>
                    <input class="form-control" asp-for="Email" />
                </div>
                <div class="form-group">
                    <label asp-for="Phone"> Your Phone please:</label>
                    <input class="form-control" asp-for="Phone" />
                </div>
                <div class="form-group">
                    <label asp-for="UserMessage">Leave a Message</label>
                    <textarea class="form-control" rows="5" asp-for="UserMessage"></textarea>
                         
                </div>
                
                <button class="btn btn-primary" type="submit">Submit</button>

            </form>
        </div>
    </div>

</body>

</html>

CommunityPage/Views/Home/History.cshtml
@{
    Layout = "_DefaultLayout";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>History</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="text-center">
        We are entering our 9th year as a fantasy league. Here are the 8 previous champions during that time

        2011-Andrew Norris
        2012-Andrew Nealon
        2013-Mac Brando
        2014-Andrew Nealon
        2015-Maren Queener
        2016-Dain Mickey
        2017-Andrew Norris
        2018-Andrew Norris
    </div>
</body>
</html>

CommunityPage/Views/Home/Important.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Important</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="text-center">
        Our Championship game this year is
        December 4th 2019. To Learn more about our league, 
        Click<a class="nav-link" href="https://fantasy.espn.com/football/league?leagueId=941432"> here</a> 
        to view the standings

    </div>
</body>
</html>

CommunityPage/Views/Home/Index.cshtml
@{
    Layout = "_DefaultLayout";
    ViewBag.Title = "Home";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="text-center">
        Welcome to the Inner-State League Fantasy Website
        <a asp-action="History">Our History</a>
        <a asp-action="Contact">Contact Us</a>
        <a asp-action="Info">Our Info</a>
        <a asp-controller="Lab6" asp-action="Index">Lab6 Controller Methods</a>

    </div>
</body>
</html>

CommunityPage/Views/Home/Info.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Info</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="center-block">
        Welcome to the Inner-State League Fantasy Website Info
        <a asp-action="Important">Important Dates</a>
        <a asp-action="People">The current members of our league</a>
    </div>
</body>
</html>

CommunityPage/Views/Home/Messages.cshtml
@model IEnumerable<CommunityPage.Models.ContactInfo>

@{
    Layout = "_SpecialLayout";
    ViewBag.Title = "Messages";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Messages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="panel-body"> <h2> Messages</h2></div>
    <div>
        <table class="table table-sm table-striped table-bordered">

            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
                @foreach (CommunityPage.Models.ContactInfo r in Model)
                {
                    <tr>
                        <td>@r.Name</td>
                        <td>@r.Email</td>
                        <td>@r.UserMessage</td>
                        
                    </tr>
                }
            </tbody>
        </table>
    </div>
    Want to send a<a class="nav-link" asp-controller="UserReply" asp-action="Replys"> reply</a> to a message?
</body>
</html>

CommunityPage/Views/Home/People.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>People</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="text-center">
        Our current members</div>
    <div class=" text-center">
        <ul>
            <li> Aaron McCarty</li>
            <li>Andrew Norris</li>
            <li>Andrew Nealon</li>
            <li>Dain Mickey</li>
            <li>Julie Mickey</li>
            <li>Chris Carlson</li>
            <li>Nathan Insko</li>
            <li>Mac Joiner</li>
            <li>Mike Queener</li>
            <li>1Maren Queener</li>
        </ul>
        <p>Our Founder is @ViewData["Founder"]</p>
    </div>
</body>
</html>

CommunityPage/Views/Home/Replys.cshtml
@model CommunityPage.Models.MessageBoards

@{
    Layout = "_SpecialLayout";
    ViewBag.Title = "UserReplys";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Contact</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="panel panel-success">
        <div class="panel-heading text-center"><h4>Want to join our league?</h4></div>"
        <div class="panel-body">
            <form class="p-a-1" asp-action="Contact" method="post">
                <div class="form-group">
                    <label asp-for="UserName"> Your Name please:</label>
                    <input class="form-control" asp-for="UserName" />
                </div>
                <div class="form-group">
                    <label asp-for="UserMessage">Leave a Message</label>
                    <textarea class="form-control" rows="5" asp-for="UserMessage"></textarea>

                </div>

                <button class="btn btn-primary" type="submit">Submit</button>

            </form>
        </div>
    </div>
    <div>
        <table class="table table-sm table-striped table-bordered">

            <thead>
                <tr>
                    <th>Name</th>
                    <th>Message</th>
                    <th>r.Time</th>
                </tr>
            </thead>

        </table>
    </div>
</body>

</html>

CommunityPage/Views/Home/Thanks.cshtml
@model CommunityPage.Models.ContactInfo

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Thanks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body class="text-center">
    <p>
        <h1> Thank you!</h1>     
    </p>
    Click<a class="nav-link" asp-action="Messages"> here</a> to see all messages.
</body>
</html>

CommunityPage/Views/Lab6/ClickBait.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

CommunityPage/Views/Lab6/EmptyData.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EmptyData</title>
</head>
<body>
</body>
</html>

CommunityPage/Views/Lab6/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Lab6Layout.cshtml";
}

<h2>Lab 6 Controller Methods</h2>
<h3>@ViewBag.Message</h3>

CommunityPage/Views/Lab6/RedirectTest.cshtml
@{
    ViewData["Title"] = "RedirectTest";
    Layout = "~/Views/Shared/_Lab6Layout.cshtml";
}

<h2>RedirectTest</h2>

CommunityPage/Views/Lab6/TextTest.cshtml
@{
    ViewData["Title"] = "TextTest";
    Layout = "~/Views/Shared/_Lab6Layout.cshtml";
}

<h2>TextTest</h2>

CommunityPage/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        #mainDiv{
            border: solid medium black;
            font-size: 18pt
        }
    </style>
</head>
<body>
    <div id="mainDiv">
        @RenderBody()
    </div>
</body>
</html>

CommunityPage/Views/Shared/_Lab6Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CommunityPage</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CommunityPage</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Lab6" asp-action="RedirectTest">Rederict Test</a></li>
                    <li><a asp-area="" asp-controller="Lab6" asp-action="EmptyData">Empty Action</a></li>
                    <li><a asp-area="" asp-controller="Lab6" asp-action="TextTest">Text Test</a></li>
                    <li><a asp-area="" asp-controller="Lab6" asp-action="ClickBait">RouteTest</a></li>
                </ul>
            </div>
        </div>
    </nav>
        <div>
            @RenderBody()
        </div>
    </body>
</html>

CommunityPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CommunityPage</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CommunityPage</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="UserReply" asp-action="Replys">Replys</a></li>
                    <li><a asp-area="" asp-controller="Lab6" asp-action="TextTest">Lab6 Views</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CommunityPage</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CommunityPage/Views/Shared/_SpecialLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        #mainDiv {
            border: solid medium green;
            font-size: 18pt
        }
    </style>
</head>
<body>
    <div id="mainDiv">
        @RenderBody()
    </div>
</body>
</html>

CommunityPage/Views/UserReply/Replys.cshtml
@model String
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Add a Reply</title>
</head>
<body>
    <h1>Review for <em>@Model</em></h1>
    <blockquote>*@ViewBag.Message</blockquote>
    <form method="post">
        <label for="usercomment">Your reply</label><br />
        <textarea type="text" name="usercomment"></textarea><br />
        <label for="name">Your name</label><br />
        <input name="name" /><br />

        <input type="submit" value="Enter" />
    </form>
</body>
</html>